# Generated by Django 5.1.5 on 2025-12-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_category_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="category_old",
            field=models.CharField(
                blank=True,
                choices=[
                    ("technology", "Technology"),
                    ("lifestyle", "Lifestyle"),
                    ("design", "Design"),
                    ("culture", "Culture"),
                    ("business", "Business"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
                null=True,
            ),
        ),
    ]
