# Generated by Django 5.1.5 on 2025-12-20 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_migrate_categories_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category_old",
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="myapp.category",
            ),
        ),
    ]
