# Generated by Django 5.2.8 on 2026-01-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_subscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="newsletter_sent",
            field=models.BooleanField(default=False),
        ),
    ]
